spring.application.name=prod-ub-cron-kafka
server.port=8081

# Kafka Bootstrap Servers (override via env SPRING_KAFKA_BOOTSTRAP_SERVERS en Docker)
spring.kafka.bootstrap-servers=localhost:29092,localhost:39092,localhost:49092

# Configuracion CRON - cada 5 minutos
ubicacion.cron.expression=0 */5 * * * *
